### ISSUE TITLE
Littera is down!

### ISSUE THREAD

**Issue by lostfictions** [Chman/Typogenic#10]
Hey! I've used Typogenic a few times before and found it really useful and nicely robust as a solution, but one point of uneasiness for me is that the documented process for creating new fonts depends on passing them through a hosted third-party solution.

Sure enough, when I tried to use [Littera](http://kvazars.com/littera/) today, it failed to load. I guess I'm out of luck -- any ideas?

**Comment by Chman** [comment]
It's working for me. The fact that it relies on a third party app is a bit concerning indeed. Note that you can actually save Littera to use it locally (it's a simple swf) if you're worried about it being down again.

**Comment by lostfictions** [comment]
Oops, I guess it was only down temporarily. I've grabbed the swf -- hadn't thought of that, so thanks for the tip.
