### ISSUE TITLE
How to set different coloured  in text

### ISSUE THREAD

**Issue by Ankitjagrawat** [Chman/Typogenic#8]

**Comment by Chman** [comment]
Using [mixed material](http://thomashourdel.com/typogenic/doc/#mixed-materials).

**Comment by Ankitjagrawat** [comment]
With Same Fonts..
like -  the "GitHub" is the good

in this note-"GitHub"  in red color and words in yellow color .with same fonts

**Comment by Chman** [comment]
Use mixed material, simply duplicate the font material and change the color there instead of the text component.
